# Generated by Django 5.0.2 on 2024-04-27 23:42

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30)),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('job', models.CharField(blank=True, max_length=100)),
                ('introduction', models.CharField(blank=True, max_length=500)),
                ('birthday', models.DateField(default='1900-01-01')),
                ('picture', models.FileField(null=True, upload_to='picture/%Y/%m/%d/')),
                ('created_at', models.DateTimeField()),
                ('upload_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 28, 8, 42, 17, 374305))),
                ('upload_at', models.DateTimeField(default=datetime.datetime(2024, 4, 28, 8, 42, 17, 374305))),
                ('goal_title', models.CharField(max_length=100)),
                ('goal_detail', models.CharField(max_length=200)),
                ('goal_condition', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 4, 28, 8, 42, 17, 374305))),
                ('upload_at', models.DateTimeField(default=datetime.datetime(2024, 4, 28, 8, 42, 17, 374305))),
                ('task_title', models.CharField(max_length=100)),
                ('task_condition', models.BooleanField(default='0')),
                ('task_priority', models.IntegerField(default='0')),
                ('task_due', models.DateField(default=django.utils.timezone.now)),
                ('goals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.goals')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
