# Generated by Django 5.0.6 on 2024-05-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_detail',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_title',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='goals',
            name='upload_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='upload_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='introduction',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='job',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='upload_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
